new tests

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -22,6 +22,8 @@ jobs:
   test:
     runs-on: ubuntu-latest
     needs: build  # Ensure that the 'test' job runs after the 'build' job completes
+    outputs:
+      test-status: ${{ job.status }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
@@ -33,4 +35,16 @@ jobs:
         run: pnpm install  # You may skip this if dependencies are already installed in 'build'
 
       - name: Tests unitaires
-        run: pnpm test
+        run: |
+          if ! pnpm test; then
+            echo "::set-output name=test-status::failure"
+            exit 1
+          fi
+
+  cancel-push:
+    runs-on: ubuntu-latest
+    needs: test  # Wait for 'test' job to complete
+    if: ${{ needs.test.outputs.test-status == 'failure' }}  # Cancel only if 'test' job fails
+    steps:
+      - name: Cancel Push
+        run: echo "Tests failed, cancelling push."
